"""Omni-Rewriter public API."""

from .adapters import (
    GenerationAdapterError,
    GenerationConfigurationError,
    GenerationResponseError,
    GenerationTooLargeError,
    GenerationTransportError,
    H3Client,
    H3ClientConfig,
    HunyuanImageVLLMClient,
    HunyuanImageVLLMClientConfig,
    ImageGeneratorAdapter,
    MiniMaxClient,
    MiniMaxClientConfig,
    OmniVideosClient,
    OmniVideosClientConfig,
    OpenAIImagesClient,
    OpenAIImagesClientConfig,
    VideoGeneratorAdapter,
    WanOmniAdapter,
)
from .agent import (
    AgentState,
    AnalysisPlan,
    RewriteAgent,
    RewriteAgentConfig,
    RewriteResult,
)
from .backends import (
    ChatBackend,
    ChatBackendConfig,
    FakeBackend,
    OpenAICompatibleBackend,
    ScriptedBackend,
)
from .config import Settings
from .errors import (
    AgentError,
    BackendConfigurationError,
    BackendError,
    BackendResponseError,
    BackendTransportError,
    MediaError,
    MediaMIMEError,
    MediaTooLargeError,
    MediaURIError,
    OmniRewriterError,
    RepairExhaustedError,
    StructuredOutputError,
)
from .evaluator import BasicEvaluator, Evaluator
from .media_input import MediaInputConfig, MediaPreparer, PreparedMedia
from .models import (
    BaseRewrite,
    ImagePEProfile,
    ImageRewrite,
    MediaReference,
    MediaRole,
    MediaType,
    Ref2VARewrite,
    RewriteOutput,
    RewriteRequest,
    SeedanceRefStyle,
    SeedanceRenderMode,
    SeedanceRewrite,
    SeedanceSubject,
    TaskType,
    VideoPEProfile,
    infer_task,
    render_seedance_output,
)
from .render import H3Renderable, render_h3_prompt
from .trace import JSONLTrace, redact

__all__ = [
    "AgentError",
    "AgentState",
    "AnalysisPlan",
    "BaseRewrite",
    "BackendConfigurationError",
    "BackendError",
    "BackendResponseError",
    "BackendTransportError",
    "BasicEvaluator",
    "ChatBackend",
    "ChatBackendConfig",
    "FakeBackend",
    "GenerationAdapterError",
    "GenerationConfigurationError",
    "GenerationResponseError",
    "GenerationTooLargeError",
    "GenerationTransportError",
    "H3Client",
    "H3ClientConfig",
    "H3Renderable",
    "HunyuanImageVLLMClient",
    "HunyuanImageVLLMClientConfig",
    "ImageGeneratorAdapter",
    "ImagePEProfile",
    "ImageRewrite",
    "JSONLTrace",
    "MediaError",
    "MediaInputConfig",
    "MediaMIMEError",
    "MediaPreparer",
    "MediaReference",
    "MediaRole",
    "MediaTooLargeError",
    "MediaType",
    "MediaURIError",
    "MiniMaxClient",
    "MiniMaxClientConfig",
    "OmniRewriterError",
    "OmniVideosClient",
    "OmniVideosClientConfig",
    "OpenAICompatibleBackend",
    "OpenAIImagesClient",
    "OpenAIImagesClientConfig",
    "PreparedMedia",
    "Ref2VARewrite",
    "RepairExhaustedError",
    "RewriteAgent",
    "RewriteAgentConfig",
    "RewriteOutput",
    "RewriteRequest",
    "RewriteResult",
    "ScriptedBackend",
    "SeedanceRefStyle",
    "SeedanceRenderMode",
    "SeedanceRewrite",
    "SeedanceSubject",
    "Settings",
    "StructuredOutputError",
    "TaskType",
    "VideoGeneratorAdapter",
    "VideoPEProfile",
    "WanOmniAdapter",
    "Evaluator",
    "infer_task",
    "redact",
    "render_h3_prompt",
    "render_seedance_output",
]

__version__ = "0.1.0"
